# These are supported funding model platforms

github: [tokoglobalteknik]
patreon: tokoglobalteknik
open_collective: tokoglobalteknik
ko_fi: tokoglobalteknik
tidelift: tokoglobalteknik
community_bridge: tokoglobalteknik
liberapay: tokoglobalteknik
issuehunt: tokoglobalteknik
otechie: tokoglobalteknik
custom: ['https://tokoglobalteknik.com/donate', 'https://tokoglobalteknik.com/support']